services:
  app:
    image: 'docker-spring-boot-mysql:latest'  # Falls du MySQL nutzt
    build:
      context: ..  # Geben Sie den Kontext an, wo die Dockerfile für die Spring Boot App liegt
    container_name: Onboarding
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-9wtg:3306/db_raiffeisen
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  angular-app:
    build:
      context: ../Onboarding_client  # Kontext für die Angular-App
    container_name: angular-app
    ports:
      - "4200:4200"
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3

