services:

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: Onboarding
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_Raiffeisen
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  angular-app:
    build:
      context: ./Onboarding_client
    ports:
      - "4200:4200"
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_Raiffeisen
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

