services:
  - name: onboarding-frontend
    type: web
    runtime: static
    repo: https://github.com/yazan1kasem/Raiffeisen_Onboarding.git
    branch: master
    buildCommand: cd Onboarding_client && npm install && ng serve -o
    staticPublishPath: Onboarding_client/dist/Onboarding_client
    envVars:
      - key: API_URL
        value: https://onboarding-backend.onrender.com
    routes:
      - source: /.*
        destination: /index.html
        type: rewrite

  - name: onboarding-backend
    type: web
    runtime: docker
    repo: https://github.com/yazan1kasem/Raiffeisen_Onboarding.git
    branch: master
    plan: starter
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: db_raiffeisen
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: db_raiffeisen
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: db_raiffeisen
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: "8081"
      - key: SECURITY_JWT_SECRET_KEY
        sync: false  # 🔒 Secret bleibt sicher
      - key: SECURITY_JWT_EXPIRATION_TIME
        value: "36000000"
    healthCheckPath: /actuator/health
    region: frankfurt
    dockerfilePath: Dockerfile
  - type: pserv
    name: db_raiffeisen
    runtime: docker
    repo: https://github.com/render-examples/mysql
    plan: starter
    branch: oh/mysql_8.0.24
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_PASSWORD
        value: root
      - key: MYSQL_USER
        value: root
      - key: MYSQL_DATABASE
        value: db_raiffeisen
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    disk:
      name: disk
      mountPath: /var/lib/mysql
      sizeGB: 10
