name: Build, Test and Deploy
#a
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_raiffeisen
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Check Database Connection
        run: |
          echo "Trying to connect to MySQL..."
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"

      - name: Install Dependencies und Run Tests (Server)
        env:
          JWT_SECRET: ${{ secrets.SECRET_KEY }}
        run: |
          cd ..
          cd Raiffeisen_Onboarding
          mvn clean install
          mvn test

      - name: Collect Server Test Reports
        run: |
          mkdir -p server-test-results
          cp target/surefire-reports/*.xml server-test-results/      
      

      # Client: Install Dependencies and Fix Vulnerabilities
      - name: Install Dependencies und Fix Vulnerabilities (Client)
        run: |
          cd Onboarding_client
          npm install
          npm audit fix || true

      # Client: Update Angular and Dependencies
      - name: Update Angular and Dependencies
        run: |
          cd Onboarding_client
          npm install -g @angular/cli@latest
          ng update @angular/core @angular/cli || true
          npm fund

      # Client: Run Angular Tests
      - name: Run Angular Tests
        run: |
          cd Onboarding_client
          npm test -- --watch=false --browsers=ChromeHeadless || true

      # Client: Collect Test Reports
      - name: Collect Client Test Reports
        run: |
          ls
          mkdir -p client-test-results
          cp Onboarding_client/test-results/*.xml client-test-results/

      # Upload Test Reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4.5.0
        with:
          name: test-reports
          path:
            server-test-results/
            client-test-results/

      - name: List Docker Images
        run: docker images
