name: Build, Test and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Setup Database
        run: |
          docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=db_Raiffeisen -p 3306:3306 mysql:5.7
      - name: Check Database Connection
        run: |
          echo "Trying to connect to MySQL..."
          mysql -h localhost -u root -proot -e "SHOW DATABASES;"

      - name: Install Dependencies und Run Tests (Server)
        env:
          JWT_SECRET: ${{ secrets.SECRET_KEY }}
        run: |
          cd ..
          cd Raiffeisen_Onboarding
          mvn clean install
          mvn test

      - name: Collect Server Test Reports
        run: |
          mkdir -p server-test-results
          cp Onboarding/target/surefire-reports/*.xml server-test-results/

      - name: Install Dependencies und Run Tests (Client)
        run: |
          cd Onboarding_client
          npm install
          npm test -- --watch=false --browsers=ChromeHeadless --reporters junit --outputPath=test-results

      - name: Collect Client Test Reports
        run: |
          mkdir -p client-test-results
          cp Onboarding_client/test-results/*.xml client-test-results/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            server-test-results/
            client-test-results/

      - name: Build Docker Images
        run: |
          docker build -t my-server-image ./Onboarding
          docker build -t my-client-image ./Onboarding_client

      - name: List Docker Images
        run: docker images
